// Actions
export const SESSION_CONNECT_WEB3 = 'SESSION_CONNECT_WEB3';

// Mutations
export const SESSION_SET_PROPERTY = 'SESSION_SET_PROPERTY';
export const SESSION_SET_PIGGY_BANKS = 'SESSION_SET_PIGGY_BANKS';
export const SESSION_CLEAR_PIGGY_BANKS = 'SESSION_CLEAR_PIGGY_BANKS';

// Getters
export const SESSION_IS_LOGGED = 'SESSION_IS_LOGGED';
